### ISSUE TITLE
Failed to install "dlookr" from Github

### ISSUE THREAD

**Issue by Godskid89** [choonghyunryu/dlookr#10]
i get this error trying to download the package

Error: Failed to install 'dlookr' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘rlang’

**Comment by choonghyunryu** [comment]
You may have 'rlang' loaded into your session already.
So restart R and then try running install again before loading 'rlang'.

**Comment by Godskid89** [comment]
Thank you. It works now

**Comment by billyarberry9999** [comment]
I could not get dlookr to install until I had also installed systemfonts. After that, no problems.

**Comment by choonghyunryu** [comment]
Hi billyarberry9999,
 
Thank you for using the dlookr package.
 
Best Regards,
Ryu
 
-----Original Message-----

**Comment by Bryan-SuiDati** [comment]
Hi @choonghyunryu 

I installed dlookr very well. But, when I use library(dlookr), get the following message.

Error: package or namespace load failed for ‘dlookr’:
.onLoad failed in loadNamespace() for 'sysfonts', details:
call: font_add("sans", sans.r, sans.b, sans.i, sans.bi, NULL)
error: freetype: cannot open resource, error code 1

Could you help me please?

**Comment by choonghyunryu** [comment]
Hi @Bryan-SuiDati,

There seems to be a problem with the sysfonts package used by dlookr.

Reinstall the relevant packages with the following command.

install.packages('sysfonts')
install.packages('showtext')

If that still doesn't solve the problem,
Please send the result of running sessionInfo().

The following URL also has related content.
https://d.cosx.org/d/419265-showtext-sysfonts/2
https://copyfuture.com/blogs-details/202202062306247813
