### ISSUE TITLE
ead_report / pdf output issue

### ISSUE THREAD

**Issue by Raymond-KT** [choonghyunryu/dlookr#12]
안녕하세요. dlookr 패키지 정말 감사히 사용하고 있습니다. 
혼자서 분석 할 때는 html로 출력하여 홀로 보면서 사용하였는데, 
팀프로젝트를 하다보니, pdf로 출력하는 것이 꼭 필요해졌습니다ㅠ

거의 2주동안 문제를 해결하기 위해 이곳저곳을 돌아다녔지만, 
해결책을 찾을 수 없어 문의 드립니다. 

초반에는 LaTex 문제인 것 같아 MikTex도 설치해보고, Texlive도 설치해보았습니다. 

현재는 Texlive 2019가 설치되어 있고, 
아래와 같이 Console 창에 메시지가 출력되었습니다. 

eda_report 함수로 pdf 출력을 꼭 해보고 싶은데, 바쁘시겠지만 도움 주신다면
정말 정말 감사하겠습니다. 

감사합니다 ㅠ

processing file: ./EDA_Report.Rnw
  |.....................................                                                                           |  33%
  ordinary text without R code

  |...........................................................................                                     |  67%
label: child-section-application (with options) 
List of 1
 $ child: chr "02_RunEDA.Rnw"

processing file: ./02_RunEDA.Rnw
  |....                                                                                                            |   4%
  ordinary text without R code

  |.........                                                                                                       |   8%
label: enrironment (with options) 
List of 3
 $ echo   : logi FALSE
 $ warning: logi FALSE
 $ message: logi FALSE

  |.............                                                                                                   |  12%
  ordinary text without R code

  |..................                                                                                              |  16%
label: check_variables (with options) 
List of 1
 $ echo: logi FALSE

  |......................                                                                                          |  20%
   inline R code fragments

  |...........................                                                                                     |  24%
label: info_variables (with options) 
List of 2
 $ echo   : logi FALSE
 $ results: chr "asis"

  |...............................                                                                                 |  28%
   inline R code fragments

  |....................................                                                                            |  32%
label: describe_univariate (with options) 
List of 3
 $ echo   : logi FALSE
 $ comment: chr ""
 $ results: chr "asis"

  |........................................                                                                        |  36%
  ordinary text without R code

  |.............................................                                                                   |  40%
label: normality (with options) 
List of 2
 $ echo   : logi FALSE
 $ results: chr "asis"

  |.................................................                                                               |  44%
  ordinary text without R code

  |......................................................                                                          |  48%
label: correlations (with options) 
List of 2
 $ echo   : logi FALSE
 $ results: chr "asis"

  |..........................................................                                                      |  52%
  ordinary text without R code

  |...............................................................                                                 |  56%
label: plot_correlations (with options) 
List of 2
 $ echo   : logi FALSE
 $ results: chr "asis"

  |...................................................................                                             |  60%
  ordinary text without R code

  |........................................................................                                        |  64%
label: numeric_variables (with options) 
List of 2
 $ echo   : logi FALSE
 $ results: chr "asis"

  |............................................................................                                    |  68%
  ordinary text without R code

  |.................................................................................                               |  72%
label: category_variables (with options) 
List of 2
 $ echo   : logi FALSE
 $ results: chr "asis"

  |.....................................................................................                           |  76%
  ordinary text without R code

  |..........................................................................................                      |  80%
label: group_correlations (with options) 
List of 2
 $ echo   : logi FALSE
 $ results: chr "asis"

  |..............................................................................................                  |  84%
  ordinary text without R code

  |...................................................................................................             |  88%
label: plot_group_correlations (with options) 
List of 2
 $ echo   : logi FALSE
 $ results: chr "asis"

  |.......................................................................................................         |  92%
  ordinary text without R code

  |............................................................................................................    |  96%
label: option_undo (with options) 
List of 1
 $ echo: logi FALSE

  |................................................................................................................| 100%
  ordinary text without R code

  |................................................................................................................| 100%
  ordinary text without R code

output file: ./EDA.tex

This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019/W32TeX) (preloaded format=pdflatex)
 restricted \write18 enabled.
Use of uninitialized value $ver in scalar chomp at C:/texlive/2019/tlpkg/TeXLive/TLWinGoo.pm line 204.
Use of uninitialized value $ver in substitution (s///) at C:/texlive/2019/tlpkg/TeXLive/TLWinGoo.pm line 205.
Use of uninitialized value $ver in substitution (s///) at C:/texlive/2019/tlpkg/TeXLive/TLWinGoo.pm line 205.
fmtutil: fmtutil is using the following fmtutil.cnf files (in precedence order):
fmtutil:   c:/texlive/2019/texmf-dist/web2c/fmtutil.cnf
fmtutil: fmtutil is using the following fmtutil.cnf file for writing changes:
fmtutil:   c:/users/6300263/.texlive2019/texmf-config/web2c/fmtutil.cnf
fmtutil [INFO]: writing formats under c:/users/6300263/.texlive2019/texmf-var/web2c
fmtutil [INFO]: --- remaking pdflatex with pdftex
Can't spawn "cmd.exe": No such file or directory at c:\texlive\2019\texmf-dist\scripts\texlive\fmtutil.pl line 598.
fmtutil [WARNING]: inifile pdflatex.ini for pdflatex/pdftex not found.
fmtutil [INFO]: Disabled formats: 6
fmtutil [INFO]: Not selected formats: 44
fmtutil [INFO]: Failed to build: 1 (pdftex/pdflatex)
fmtutil [INFO]: Total formats: 51
fmtutil [INFO]: exiting with status 1
C:\texlive\2019\bin\win32\runscript.tlu:902: command failed with exit code 1:
perl.exe c:\texlive\2019\texmf-dist\scripts\texlive\fmtutil.pl  --user --byfmt pdflatex
Running the command C:\texlive\2019\bin\win32\fmtutil-user.exe
I can't find the format file `pdflatex.fmt'!

kpathsea: Running mktexfmt pdflatex.fmt

The command name is C:\texlive\2019\bin\win32\mktexfmt
I was unable to find any missing LaTeX packages from the error log EDA.log.
! Use of uninitialized value $ver in scalar chomp at C:/texlive/2019/tlpkg/TeXLive/TLWinGoo.pm line 204.
! Use of uninitialized value $ver in substitution (s///) at C:/texlive/2019/tlpkg/TeXLive/TLWinGoo.pm line 205.
! Use of uninitialized value $ver in substitution (s///) at C:/texlive/2019/tlpkg/TeXLive/TLWinGoo.pm line 205.
! fmtutil: fmtutil is using the following fmtutil.cnf files (in precedence order):
! fmtutil:   c:/texlive/2019/texmf-dist/web2c/fmtutil.cnf
! fmtutil: fmtutil is using the following fmtutil.cnf file for writing changes:
! fmtutil:   c:/users/6300263/.texlive2019/texmf-config/web2c/fmtutil.cnf
! fmtutil [INFO]: writing formats under c:/users/6300263/.texlive2019/texmf-var/web2c
! fmtutil [INFO]: --- remaking pdflatex with pdftex
! Can't spawn "cmd.exe": No such file or directory at c:\texlive\2019\texmf-dist\scripts\texlive\fmtutil.pl line 598.
! fmtutil [WARNING]: inifile pdflatex.ini for pdflatex/pdftex not found.
! fmtutil [INFO]: Disabled formats: 6
! fmtutil [INFO]: Not selected formats: 44
! fmtutil [INFO]: Failed to build: 1 (pdftex/pdflatex)
! fmtutil [INFO]: Total formats: 51
! fmtutil [INFO]: exiting with status 1
! C:\texlive\2019\bin\win32\runscript.tlu:902: command failed with exit code 1:
! perl.exe c:\texlive\2019\texmf-dist\scripts\texlive\fmtutil.pl  --user --byfmt pdflatex
! Running the command C:\texlive\2019\bin\win32\fmtutil-user.exe

! Use of uninitialized value $ver in substitution (s///) at C:/texlive/2019/tlpkg/TeXLive/TLWinGoo.pm line 205.
! Use of uninitialized value $ver in substitution (s///) at C:/texlive/2019/tlpkg/TeXLive/TLWinGoo.pm line 205.
! fmtutil: fmtutil is using the following fmtutil.cnf files (in precedence order):
! fmtutil:   c:/texlive/2019/texmf-dist/web2c/fmtutil.cnf
! fmtutil: fmtutil is using the following fmtutil.cnf file for writing changes:
! fmtutil:   c:/users/6300263/.texlive2019/texmf-config/web2c/fmtutil.cnf
! fmtutil [INFO]: writing formats under c:/users/6300263/.texlive2019/texmf-var/web2c
! fmtutil [INFO]: --- remaking pdflatex with pdftex
! Can't spawn "cmd.exe": No such file or directory at c:\texlive\2019\texmf-dist\scripts\texlive\fmtutil.pl line 598.
! fmtutil [WARNING]: inifile pdflatex.ini for pdflatex/pdftex not found.
! fmtutil [INFO]: Disabled formats: 6
! fmtutil [INFO]: Not selected formats: 44
! fmtutil [INFO]: Failed to build: 1 (pdftex/pdflatex)
! fmtutil [INFO]: Total formats: 51
! fmtutil [INFO]: exiting with status 1
! C:\texlive\2019\bin\win32\runscript.tlu:902: command failed with exit code 1:
! perl.exe c:\texlive\2019\texmf-dist\scripts\texlive\fmtutil.pl  --user --byfmt pdflatex
! Running the command C:\texlive\2019\bin\win32\fmtutil-user.exe

! Use of uninitialized value $ver in substitution (s///) at C:/texlive/2019/tlpkg/TeXLive/TLWinGoo.pm line 205.
! fmtutil: fmtutil is using the following fmtutil.cnf files (in precedence order):
! fmtutil:   c:/texlive/2019/texmf-dist/web2c/fmtutil.cnf
! fmtutil: fmtutil is using the following fmtutil.cnf file for writing changes:
! fmtutil:   c:/users/6300263/.texlive2019/texmf-config/web2c/fmtutil.cnf
! fmtutil [INFO]: writing formats under c:/users/6300263/.texlive2019/texmf-var/web2c
! fmtutil [INFO]: --- remaking pdflatex with pdftex
! Can't spawn "cmd.exe": No such file or directory at c:\texlive\2019\texmf-dist\scripts\texlive\fmtutil.pl line 598.
! fmtutil [WARNING]: inifile pdflatex.ini for pdflatex/pdftex not found.
! fmtutil [INFO]: Disabled formats: 6
! fmtutil [INFO]: Not selected formats: 44
! fmtutil [INFO]: Failed to build: 1 (pdftex/pdflatex)
! fmtutil [INFO]: Total formats: 51
! fmtutil [INFO]: exiting with status 1
! C:\texlive\2019\bin\win32\runscript.tlu:902: command failed with exit code 1:
! perl.exe c:\texlive\2019\texmf-dist\scripts\texlive\fmtutil.pl  --user --byfmt pdflatex
! Running the command C:\texlive\2019\bin\win32\fmtutil-user.exe

! fmtutil: fmtutil is using the following fmtutil.cnf files (in precedence order):
! fmtutil:   c:/texlive/2019/texmf-dist/web2c/fmtutil.cnf
! fmtutil: fmtutil is using the following fmtutil.cnf file for writing changes:
! fmtutil:   c:/users/6300263/.texlive2019/texmf-config/web2c/fmtutil.cnf
! fmtutil [INFO]: writing formats under c:/users/6300263/.texlive2019/texmf-var/web2c
! fmtutil [INFO]: --- remaking pdflatex with pdftex
! Can't spawn "cmd.exe": No such file or directory at c:\texlive\2019\texmf-dist\scripts\texlive\fmtutil.pl line 598.
! fmtutil [WARNING]: inifile pdflatex.ini for pdflatex/pdftex not found.
! fmtutil [INFO]: Disabled formats: 6
! fmtutil [INFO]: Not selected formats: 44
! fmtutil [INFO]: Failed to build: 1 (pdftex/pdflatex)
! fmtutil [INFO]: Total formats: 51
! fmtutil [INFO]: exiting with status 1
! C:\texlive\2019\bin\win32\runscript.tlu:902: command failed with exit code 1:
! perl.exe c:\texlive\2019\texmf-dist\scripts\texlive\fmtutil.pl  --user --byfmt pdflatex
! Running the command C:\texlive\2019\bin\win32\fmtutil-user.exe

! fmtutil:   c:/texlive/2019/texmf-dist/web2c/fmtutil.cnf
! fmtutil: fmtutil is using the following fmtutil.cnf file for writing changes:
! fmtutil:   c:/users/6300263/.texlive2019/texmf-config/web2c/fmtutil.cnf
! fmtutil [INFO]: writing formats under c:/users/6300263/.texlive2019/texmf-var/web2c
! fmtutil [INFO]: --- remaking pdflatex with pdftex
! Can't spawn "cmd.exe": No such file or directory at c:\texlive\2019\texmf-dist\scripts\texlive\fmtutil.pl line 598.
! fmtutil [WARNING]: inifile pdflatex.ini for pdflatex/pdftex not found.
! fmtutil [INFO]: Disabled formats: 6
! fmtutil [INFO]: Not selected formats: 44
! fmtutil [INFO]: Failed to build: 1 (pdftex/pdflatex)
! fmtutil [INFO]: Total formats: 51
! fmtutil [INFO]: exiting with status 1
! C:\texlive\2019\bin\win32\runscript.tlu:902: command failed with exit code 1:
! perl.exe c:\texlive\2019\texmf-dist\scripts\texlive\fmtutil.pl  --user --byfmt pdflatex
! Running the command C:\texlive\2019\bin\win32\fmtutil-user.exe

! fmtutil: fmtutil is using the following fmtutil.cnf file for writing changes:
! fmtutil:   c:/users/6300263/.texlive2019/texmf-config/web2c/fmtutil.cnf
! fmtutil [INFO]: writing formats under c:/users/6300263/.texlive2019/texmf-var/web2c
! fmtutil [INFO]: --- remaking pdflatex with pdftex
! Can't spawn "cmd.exe": No such file or directory at c:\texlive\2019\texmf-dist\scripts\texlive\fmtutil.pl line 598.
! fmtutil [WARNING]: inifile pdflatex.ini for pdflatex/pdftex not found.
! fmtutil [INFO]: Disabled formats: 6
! fmtutil [INFO]: Not selected formats: 44
! fmtutil [INFO]: Failed to build: 1 (pdftex/pdflatex)
! fmtutil [INFO]: Total formats: 51
! fmtutil [INFO]: exiting with status 1
! C:\texlive\2019\bin\win32\runscript.tlu:902: command failed with exit code 1:
! perl.exe c:\texlive\2019\texmf-dist\scripts\texlive\fmtutil.pl  --user --byfmt pdflatex
! Running the command C:\texlive\2019\bin\win32\fmtutil-user.exe

! fmtutil:   c:/users/6300263/.texlive2019/texmf-config/web2c/fmtutil.cnf
! fmtutil [INFO]: writing formats under c:/users/6300263/.texlive2019/texmf-var/web2c
! fmtutil [INFO]: --- remaking pdflatex with pdftex
! Can't spawn "cmd.exe": No such file or directory at c:\texlive\2019\texmf-dist\scripts\texlive\fmtutil.pl line 598.
! fmtutil [WARNING]: inifile pdflatex.ini for pdflatex/pdftex not found.
! fmtutil [INFO]: Disabled formats: 6
! fmtutil [INFO]: Not selected formats: 44
! fmtutil [INFO]: Failed to build: 1 (pdftex/pdflatex)
! fmtutil [INFO]: Total formats: 51
! fmtutil [INFO]: exiting with status 1
! C:\texlive\2019\bin\win32\runscript.tlu:902: command failed with exit code 1:
! perl.exe c:\texlive\2019\texmf-dist\scripts\texlive\fmtutil.pl  --user --byfmt pdflatex
! Running the command C:\texlive\2019\bin\win32\fmtutil-user.exe

! fmtutil [INFO]: writing formats under c:/users/6300263/.texlive2019/texmf-var/web2c
! fmtutil [INFO]: --- remaking pdflatex with pdftex
! Can't spawn "cmd.exe": No such file or directory at c:\texlive\2019\texmf-dist\scripts\texlive\fmtutil.pl line 598.
! fmtutil [WARNING]: inifile pdflatex.ini for pdflatex/pdftex not found.
! fmtutil [INFO]: Disabled formats: 6
! fmtutil [INFO]: Not selected formats: 44
! fmtutil [INFO]: Failed to build: 1 (pdftex/pdflatex)
! 에러: LaTeX failed to compile EDA.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See EDA.log for more info.
추가정보: 경고메시지(들): 
In dir.create(paste(path, "figure", sep = "/")) :
  '.\figure'은 이미 존재합니다

**Comment by choonghyunryu** [comment]
Ms-Windows 및 Texlive 설치된 환경좀 알려주세요.

그리고, 관리자 권한으로 윈도우즈 콘솔에서 다음 명령어를 수행해 보세요.
fmtutil -sys --all

**Comment by Raymond-KT** [comment]
안녕하세요. Windows10에 설치하였으며, C:\texlive\2019 에 설치 되어 있습니다. 

fmtutil -sys --all 실행하여 설치 완료 하였고, pdf로 잘 출력됩니다 ㅠ
감사합니다!

데이터 상에 demography 정보가 character로 들어가 있었는데, 
해당 컬럼을 제거하고, integer로만 데이터셋 구성하여 실행하니, 
보고서가 잘 생성 됩니다!!!!

감사합니다 !!!

**Comment by choonghyunryu** [comment]
Latex 설치가 완전하지 못해서 발생했던 오류입니다.
한글 운영체제 및 MS-Windows 환경에서는 가끔 이런저런 이슈가 발생합니다.

저는 회사에서는 CentOS Linux, 개인적으로는 Mac을 사용하고 있답니다.

"데이터 상에 demography 정보가 character로 들어가 있었는데,
해당 컬럼을 제거하고, integer로만 데이터셋 구성하여 실행하니,
보고서가 잘 생성 됩니다!!!!"

이 의미를 잘 모르겠네요. 좀 더 구체적으로 설명해 주실 수 있나요?

**Comment by Raymond-KT** [comment]
아! 네!! 제가 HR 데이터로 dlookr를 돌려보았는데, 
데이터 중에 직급을 표시한 컬럼와, 소속 회사를 표시한 컬럼이 들어가 있으면 
에러가 나면서 최종 pdf가 안만들어졌습니다. 

문자열로 된 컬럼을 모두 지우고 실행하니 잘 되어서, 해당 내용을 말씀 드린 것 입니다. 

감사합니다 !!

**Comment by choonghyunryu** [comment]
감사합니다. character type의 데이터가 포함되어 있을 때의 이슈를 살펴보겠습니다.
문제가 있으면, 버그를 수정하겠습니다.

감사합니다.
