### ISSUE TITLE
A new binning type based on gain ratio

### ISSUE THREAD

**Issue by lucazav** [choonghyunryu/dlookr#15]
It'd be great if the `binning()` function had a type of binning based on [gain ration maximization](https://blog.datascienceheroes.com/discretization-recursive-gain-ratio-maximization/).
Here an example of the [`discretize_rgr()`](https://github.com/pablo14/funModeling/blob/master/R/discretize.R) function implemented into the `funModeling` package.

**Comment by choonghyunryu** [comment]
@lucazav
Thanks for the great feature suggestion.
I will add the features you suggested to the next version.

**Comment by choonghyunryu** [comment]
I close the issue because I implemented that function.
