### ISSUE TITLE
Troubles with relate() function

### ISSUE THREAD

**Issue by jgduenasl** [choonghyunryu/dlookr#16]
I have a data frame df with two categorical variables: var1 and var2. I am following the tutorial to get the contingency table taking var1 as target and var2 as predictor. When I run

target <- target_by(df, var1)
tc <-  relate(target, var2)
> tc
the latter gives me:
function (.data, predictor) 
{
    UseMethod("relate", .data)
}
<bytecode: 0x7fa4ad372e40>
<environment: namespace:dlookr>

and running summary(etc) gives me the error:
Error in object[[i]] : object of type 'closure' is not subsettable

I am not understanding what is happening.
I appreciate your help in advance

**Comment by choonghyunryu** [comment]
@jgduenasl ,

Can you share data? Or please give a detailed description of the data structure.

**Comment by jgduenasl** [comment]
@choonghyunryu ,
Unfortunately, I can not share the data, but the structure is a single table each record decoding an excombatant, where I am using the variable sex as target and age as predictor. The whole table as data frame has 654 variables and I named rnr_df. Then I am calling the functions as
target_rnr_df <- target_by(rnr_df,sex)
sex_age <- relate(target_rnrn_df, age)
sex_age_ct <- summary(sex_age)
and gives me the above message errors

**Comment by choonghyunryu** [comment]
@jgduenasl 

Can you share the results of running the script below?
It is necessary to solve the problem.

summary(rnr_df[, c("sex", "age")])
is(rnr_df$sex)
table(rnr_df$sex)
is(rnr_df$age)

**Comment by choonghyunryu** [comment]
@jgduenasl 

I did find cause.
The categorical variable to be used as an argument of target_by() only supports ordered and factor.
However, the type of sex is not a factor, but a character.

Perform rnr_df$sex <-factor (rnr_df$sex) first, then proceed.

I will include logic to check this in the next version.

**Comment by choonghyunryu** [comment]
relate() fixed error when using character type as a categorical variable (@jgduenasl, #14).

**Comment by jgduenasl** [comment]
Sorry for the delayed reply. 
running the scripts you said above, I find the next results:
> summary(rnr_df[, c("sex_rnec", "age_rnec")])
  sex_rnec          age_rnec        
 Length:11657       Length:11657      
 Class :character   Class :character  
 Mode  :character   Mode  :character 
> is(rnr_df$sex_rnec)
[1] "character"           "vector"              "data.frameRowLabels" "SuperClassMethod"    "index"              
[6] "atomicVector"       
> is(rnr_df$age_rnec)
[1] "character"           "vector"              "data.frameRowLabels" "SuperClassMethod"    "index"              
[6] "atomicVector" 
> table(rnr_df$sex_rnec)
 Femenino Masculino 
     2865      8792 

Then, when I call the target_by() and relate() functions they run well. However, when running summary happens this:
> t_dpto <- target_by(rnr_df,sex_rnec)
> dpto_age <- relate(t_dpto, age_rnec)
> summary(dpto_age)
Error in object[[i]] : object of type 'closure' is not subsettable

After converting both variables as a factor as you suggest and running again the functions, the result is
> summary(dpto_age)
Call: xtabs(formula = formula_str, data = data, addNA = TRUE)
Number of cases in table: 11657 
Number of factors: 2 
Test for independence of all factors:
	Chisq = 566.3, df = 68, p-value = 1.135e-79
	Chi-squared approximation may be incorrect

Then it fixes this issue. Thus, I need to convert all character variables as a factor to apply these functions. I appreciate your support.
