### ISSUE TITLE
Misspelled Word: Gruoped

### ISSUE THREAD

**Issue by hangtime79** [choonghyunryu/dlookr#2]
In a few locations in the EDA Report, the headings use "Gruoped" instead of Grouped. These headings are:

4.1 **Gruoped** Descriptive Statistics
4.1.1 **Gruoped** Numerical Variables
There is no target variable.

4.1.2 **Gruoped** Categorical Variables
There is no target variable.

4.2 **Gruoped** Relationship Between Variables

**Comment by choonghyunryu** [comment]
Thank you. hangtime79

Corrected headings typo in EDA Report.

Thank you for your advice.
