### ISSUE TITLE
Adding Box-Cox plots to plot_normality() and Box-Cox transformation to transform()

### ISSUE THREAD

**Issue by lucazav** [choonghyunryu/dlookr#21]
Providing the `transform()` function with the box-cox transformation, finding the best lambda automatically, could be useful too. Also storing the found values in attributes for the dataframe (referring the transformed variable) could be useful to do a reverse transformation later on.
It'd be useful to show also box-cox transformed plots in `plot_normality()` output.

**Comment by choonghyunryu** [comment]
@lucazav 

Thank you so much.
I will append your recommend functions.

**Comment by zhjx19** [comment]
@choonghyunryu 
And another: Yeo-Johnson transformation, similar to the Box-Cox but does not require the input variables to be strictly positive.

**Comment by choonghyunryu** [comment]
@zhjx19 

Thank you so much.
I will append your recommend functions.

**Comment by choonghyunryu** [comment]
@lucazav, @zhjx19 
 
I added that feature to version 0.3.15 of dlookr on github.
