### ISSUE TITLE
The title of a graph may be wrong.

### ISSUE THREAD

**Issue by MarioPrado1148** [choonghyunryu/dlookr#26]
I made a log transform of a feature called 'totalVenda'.

totalVenda_log = transform(df$totalVenda, method = "log")
summary(totalVenda_log)

After doing that, I made a plot.
plot(totalVenda_log)

The above command produces two graphs.
The left one is called 'Oraginal Data'.

I think it is supposed to be called 'Original Data' instead.

My best regards, Mario (Brazil)

**Comment by choonghyunryu** [comment]
Hi @MarioPrado1148 

Thanks for you recommend.
I fixed it in github repository, and I will submit CRAN later.

Best Regards,
Choonghyun
