### ISSUE TITLE
Error in eda_report

### ISSUE THREAD

**Issue by EvanLuff** [choonghyunryu/dlookr#27]
Hello,

When eda_report is run on a data set that has two numerical variables, both of which have some null values but not all entries are null and one of which is set to that target variable, the resulting error occurs: "Error in apply(edaData[, idx.numeric], 2, function(x) !all(is.na(x))) : dim(X) must have a positive length". The code supplied in the error traces back to lines 87-95 in EDA_Report.Rmd. The solution was to wrap edaData[, idx.numeric] with as.data.frame(). Please see below.

idx.numeric <- idx.numeric[apply(as.data.frame(edaData[, idx.numeric]), 2,
                                 function(x) !all(is.na(x)))]

idx.numeric <- idx.numeric[apply(as.data.frame(edaData[, idx.numeric]), 2,
                                 function(x) diff(range(x, na.rm = TRUE)) > 0)]

Thank you for your work, I find dlookr to be very useful.

Best,

Evan Luff

**Comment by choonghyunryu** [comment]
Hello @EvanLuff,

Thank you so much, your comment.
I will update after fixing the bug.

Best,
Choonghyun

**Comment by choonghyunryu** [comment]
Hello @EvanLuff,

I  fixed the bug. and upload to github.
I'll submit it on CRAN later.

Best,
Choonghyun
