### ISSUE TITLE
[Feature request] Cramer's V, Theil's U, Point-Biseral and PPS in correlate() and plot_correlate()

### ISSUE THREAD

**Issue by lucazav** [choonghyunryu/dlookr#28]
This is a "generalization" of my requests made [here](https://github.com/choonghyunryu/dlookr/issues/22) and [here](https://github.com/choonghyunryu/dlookr/issues/20).

It would be great to be able to use the `correlate()` and `plot_correlate()` functions to calculate/plot the correlation between categorical variables using [_Cramer's V_](https://stackoverflow.com/questions/52554336/plot-the-equivalent-of-correlation-matrix-for-factors-categorical-data-and-mi/52557631#52557631) or [_Theil's U_](https://rstudio-pubs-static.s3.amazonaws.com/558925_38b86f0530c9480fad4d029a4e4aea68.html#thiels-u-correlation-coefficient-uncertainty-coefficient) factors.

Both the upon mentioned functions could be also used to calculate/plot the correlation between categorical and numerical variables using the [_Point-Biseral correlation_](https://www.statology.org/point-biserial-correlation-r/).

In order to get the order of association between any variable of any kind, it'd be great also to introduce the [_Predictive Power Score_](https://paulvanderlaken.com/2021/01/12/ppsr-r-package-predictive-power-score/) (PPS) in both the upon mentioned functions. Pros and cons of _PPS_ could be find [here](https://towardsdatascience.com/using-the-predictive-power-score-in-r-26c43d05dc01).

**Comment by choonghyunryu** [comment]
Finished issue in version 0.5.5
