### ISSUE TITLE
Problem of producing pdf report

### ISSUE THREAD

**Issue by MarcNiebel** [choonghyunryu/dlookr#29]
With the below code:
removed_chronic_patients %>%
    eda_report(target=spont_clearance,output_format="pdf",
               output_file="EDA_report.pdf",
               output_dir="Output/")
I am getting the following error:
output file: Output//EDA_report.tex

! LaTeX Error: Something's wrong--perhaps a missing \item.

Error: LaTeX failed to compile EDA_report.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See EDA_report.log for more info.

I am aware this is probably an LaTex issue. I have checked if any LaTex packages are missing with no avail. Was wondering if you have any experience with error above? I have also attached the error log.
[EDA_report.log](https://github.com/choonghyunryu/dlookr/files/5893697/EDA_report.log)

**Comment by choonghyunryu** [comment]
Dear MarcNiebel,

Can you share the EDA_report.tex file so that we can determine the exact cause?
And I uploaded 0.4.1 to github, try a fresh install. There was an error in version 0.4.0, so I patched it up.
