### ISSUE TITLE
Feature Request: Pass Color to "Plot" functions 

### ISSUE THREAD

**Issue by hangtime79** [choonghyunryu/dlookr#3]
For the Plot functions: I would like to see added an additional parameter, colorm that would default pass to col = "lightblue", but could take another color instead for example "mediumblue".

Example:
```
   plot_outliers <- function(df, var, colorselect = "lightblue") {
    x <- pull(df, var)
    op <- par(no.readonly = TRUE)
    par(mfrow = c(2, 2), oma = c(0, 0, 3, 0), mar = c(2, 4, 2, 2))
    on.exit(par(op))
    boxplot(x, main = "With outliers", col = colorselect)...
```

**Comment by choonghyunryu** [comment]
Thanks hangtime79.
 
I added the col argument to the plot_outlier() function in version 0.3.1 of dlookr. This argument allows you to draw a plot with the color you specify.
