### ISSUE TITLE
plot_outlier() not outputting correct label name

### ISSUE THREAD

**Issue by jmanacup** [choonghyunryu/dlookr#41]
Good day,

Using the guide on both on the readme of the github and the data quality diagnosis vignette, under **visualization of outliers using `plot_outlier()`**, the label name does not correctly match with the specified numerical diagnosis when seeing the plot.  You'll see that the Outlier Diagnosis Plot has 2 rows and 2 columns.  The first column, 2nd row plot should be labeled "Without outliers", but is labeled "with outliers" since we are following,

- With outliers box plot
- Without outliers box plot
- With outliers histogram
- Without outliers histogram

![pic](https://user-images.githubusercontent.com/44129744/118414274-3ca1f380-b669-11eb-952c-103c8292079b.png)

**Comment by choonghyunryu** [comment]
@jmanacup 
Thank you so much.

It's miss typo. 
I will fix it, at next version.

Have a nice day.

**Comment by choonghyunryu** [comment]
Fixed a miss typo in plot_outlier().
