### ISSUE TITLE
x axis overlaps labels

### ISSUE THREAD

**Issue by verajosemanuel** [choonghyunryu/dlookr#45]
When plotting bins, x-axis labels tend to overlap when figures are long.

A good fix would be to allow rotating labels to some degree or disabling scientific notation on plots.

```
bin <- binning_by(bindf, "target", "predicted")

plot(bin)

```
![plot](https://user-images.githubusercontent.com/15836677/125784728-a6eab126-4281-42bd-9b82-a3b9b36bbcf0.png)

**Comment by choonghyunryu** [comment]
@verajosemanuel,
Thank you so much, your advice.
I will fix the problem.

**Comment by choonghyunryu** [comment]
@verajosemanuel,

I added a 'rotate_angle' argument to plot.optimal_bins() that specifies the rotation angle of the x-axis labels. The default value for this argument is 0, which does not rotate labels.

Use it like following:
plot(bin, rotate_angle = 45)

It has already been applied to the github version. CRAN will be applied on the next submit.

Best Regards,
choonghyun

**Comment by verajosemanuel** [comment]
Thanks a lot choonghyun!

**Comment by verajosemanuel** [comment]
unable to install latest dev version:
```

** building package indices
** installing vignettes
   'EDA.Rmd' using 'UTF-8' 
   'Introduce.Rmd' using 'UTF-8' 
   'diagonosis.Rmd' using 'UTF-8' 
   'transformation.Rmd' using 'UTF-8' 
** testing if installed package can be loaded from temporary location
*** arch - i386
Error: package or namespace load failed for 'dlookr' in library.dynam(lib, package, package.lib):
 DLL 'colorspace' not found: maybe not installed for this architecture?
Error: loading failed
Ejecución interrumpida
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'C:/Users/joe/Documents/projectA/renv/library/R-4.0/x86_64-w64-mingw32/dlookr'
* restoring previous 'C:/Users/joe/Documents/projectA/renv/library/R-4.0/x86_64-w64-mingw32/dlookr'
Warning messages:
1: In untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
3: In i.p(...) :
  installation of package ‘C:/Users/joe/AppData/Local/Temp/RtmpUz09CB/file1444290ffd5/dlookr_0.5.0.tar.gz’ had non-zero exit status
> library(colorspace)
```

library colorspace is installed and available.
