### ISSUE TITLE
Why didn't you use data.table? Can't run your code because computer crashes.

### ISSUE THREAD

**Issue by AdrianAntico** [choonghyunryu/dlookr#46]

**Comment by choonghyunryu** [comment]
@AdrianAntico 

Thanks your comment.

dlookr supports collaboration with tidyverse packages. So it works perfectly with dplyr, which is slower than data.table.
And please tell me the details of the computer crashes.

**Comment by AdrianAntico** [comment]
@choonghyunryu dplyr is slower but I think the bigger issue is the memory consumption that dplyr uses that is the bigger constraint. If you use data.table for wrangling you will enable your package to be used with much much bigger data sets, and have everything run faster as well.

Check out the benchmark and you can see with bigger data dplyr begins to choke... https://h2oai.github.io/db-benchmark/

**Comment by verajosemanuel** [comment]
@AdrianAntico  If you consider data.table is best for your case, just use dtplyr for wrangling as this wraps data.table into dplyr workflow. Asking the author to adapt the package to your liking and not providing a reprex seems a bit rude.


Regards

**Comment by AdrianAntico** [comment]
@verajosemanuel Not sure how that helps. I already use data.table, but the purpose of the issue creation is to see if the author is willing to convert the package data wrangling code to a more efficient library so that people with bigger data can utilize it (or conversely, people with fixed compute resources).

**Comment by verajosemanuel** [comment]
This package is tidyverse friendly, so using dtplyr you are really using data.table with dlookr.
The author is not working for free to fit all our needs. This is not a bug and you do not provide a reprex.

**Comment by AdrianAntico** [comment]
@verajosemanuel I'm sorry but who are you? Do you own or contribute to this package? I brought the data limitation to the package author's attention, not yours. If he chooses not to enhance it then so be it but you're contribution to this discussion hasn't added any value.

**Comment by verajosemanuel** [comment]
Just trying to help your computer crash.

https://github.com/tidyverse/dtplyr

**Comment by AdrianAntico** [comment]
@verajosemanuel dlookr has a lot of data wrangling code running inside the functions and if that code isn't optimized then people with bigger data will run into trouble. My advice would be for @choonghyunryu to consider using data.table operations for those data wrangling steps internally. I'm even happy to help code some of it up too.

**Comment by choonghyunryu** [comment]
thanks @AdrianAntico, @verajosemanuel.

I already know that dlookr performs very slowly on large data and is very resource intensive. And I take it seriously.
There is no problem with the toy dataset, but we acknowledge that there are limitations in the large data used by the company.

But I will keep the tidyverse friendly concept.

As suggested by @verajosemanuel, I will consider whether the dtplyr package can be an alternative to this issue.
I will prioritize work to improve the speed of dlookr in future versions.

**Comment by AdrianAntico** [comment]
@choonghyunryu Thanks for the reply. Another option to dtplyr is the tidytable package that also utilizes data.table under the hood. I'm not sure if one is more mature than the other or if one has more functionality than the other, but nonetheless it's another option. https://cran.r-project.org/web/packages/tidytable/index.html
