### ISSUE TITLE
Launches XQuartz

### ISSUE THREAD

**Issue by gregleleu** [choonghyunryu/dlookr#5]
Hi, 
Is there a specific reason why `dlookr` launches XQuartz?
I'm on OS X 10.14, the icon appears on the dock, but beyond that I don't understand why it needs to call XQuartz.

I really like the package, thanks!

**Comment by choonghyunryu** [comment]
Hi gregleleu,

Sorry for the late reply.

Import the smbinning package for the dlookr package.
However, smbinning imports sqldf, and sqldf imports the tcltk package.
The tcltk package launches the XQuartz.

This means that:
dlook --> smbinning --> sqldf --> tclck --> "launches XQuartz"

best regards,
choonghyun
