### ISSUE TITLE
show.missing.combinations = TRUE for describe() used with group_by()

### ISSUE THREAD

**Issue by SchmidtPaul** [choonghyunryu/dlookr#59]
Hi, fantastic package!
I think there is no option to get the `describe()` output for all combinations of groups, i.e. including group combinations that are missing from the data, right?

``` r
library(dlookr)
library(janitor)
library(tidyverse)

# there are 6 potential combinations
mtcars %>% 
  janitor::tabyl(gear, am)
#>  gear  0 1
#>     3 15 0
#>     4  4 8
#>     5  0 5

# but only those 4 with data are shown
mtcars %>% 
  group_by(gear, am) %>% 
  dlookr::describe(mpg)
#> # A tibble: 4 x 28
#>   variable  gear    am     n    na  mean    sd se_mean   IQR skewness kurtosis
#>   <chr>    <dbl> <dbl> <int> <int> <dbl> <dbl>   <dbl> <dbl>    <dbl>    <dbl>
#> 1 mpg          3     0    15     0  16.1  3.37   0.871  3.9   -0.0910   -0.381
#> 2 mpg          4     0     4     0  21.0  3.07   1.53   4.35   0.0529   -3.79 
#> 3 mpg          4     1     8     0  26.3  5.41   1.91   9.6    0.352    -1.97 
#> 4 mpg          5     1     5     0  21.4  6.66   2.98  10.2    0.556    -1.83 
#> # ... with 17 more variables: p00 <dbl>, p01 <dbl>, p05 <dbl>, p10 <dbl>,
#> #   p20 <dbl>, p25 <dbl>, p30 <dbl>, p40 <dbl>, p50 <dbl>, p60 <dbl>,
#> #   p70 <dbl>, p75 <dbl>, p80 <dbl>, p90 <dbl>, p95 <dbl>, p99 <dbl>,
#> #   p100 <dbl>
```

Ideally, I could simply add something like `show.missing.combinations = TRUE` to `describe()` and obtain an output that looks something like this:

``` r
left_join(
  x = expand_grid(gear = unique(mtcars$gear),
                  am = unique(mtcars$am)),
  y = mtcars %>%
    group_by(gear, am) %>%
    dlookr::describe(mpg),
  by = c("gear", "am")
) %>%
  mutate(variable = "mpg",
         n = if_else(is.na(n), as.integer(0), n))
#> # A tibble: 6 x 28
#>    gear    am variable     n    na  mean    sd se_mean   IQR skewness kurtosis
#>   <dbl> <dbl> <chr>    <int> <int> <dbl> <dbl>   <dbl> <dbl>    <dbl>    <dbl>
#> 1     4     1 mpg          8     0  26.3  5.41   1.91   9.6    0.352    -1.97 
#> 2     4     0 mpg          4     0  21.0  3.07   1.53   4.35   0.0529   -3.79 
#> 3     3     1 mpg          0    NA  NA   NA     NA     NA     NA        NA    
#> 4     3     0 mpg         15     0  16.1  3.37   0.871  3.9   -0.0910   -0.381
#> 5     5     1 mpg          5     0  21.4  6.66   2.98  10.2    0.556    -1.83 
#> 6     5     0 mpg          0    NA  NA   NA     NA     NA     NA        NA    
#> # ... with 17 more variables: p00 <dbl>, p01 <dbl>, p05 <dbl>, p10 <dbl>,
#> #   p20 <dbl>, p25 <dbl>, p30 <dbl>, p40 <dbl>, p50 <dbl>, p60 <dbl>,
#> #   p70 <dbl>, p75 <dbl>, p80 <dbl>, p90 <dbl>, p95 <dbl>, p99 <dbl>,
#> #   p100 <dbl>
```

<sup>Created on 2021-11-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Do you think this would be a useful addition?

**Comment by choonghyunryu** [comment]
@SchmidtPaul,

Thanks for your suggestion. That's a great suggestion.

dlookr::describe() is a function that calculates descriptive statistics of numeric variables.
And when this function is combined with dplyr::group_by(), it calculates the descriptive statistics of numeric variables for each combination of categorical variables.

The intention of the data analyst here is to discover that the distribution of a numeric variable differs from that of others in certain combinations of categorical variables.

Of course, as you intend, finding missing cases in all possible combinations of categorical variables is one of the important attempts in data analysis.

However, your suggestion was not taken into account when designing dlookr::describe().

How about using dlookr::compare_category() to find missing cases in all possible combinations of categorical variables?

``` r
library(tidyverse)

mtcars %>% 
  mutate(gear = factor(gear)) %>% 
  mutate(am = factor(am)) %>%
  dlookr::compare_category() %>% 
  summary()
#> ── Contingency tables ───────────────────────────── Number of table is 1 ──
#> $`am vs gear`
#>    gear
#> am   3  4  5
#>   0 15  4  0
#>   1  0  8  5
#> 
#> ── Relative contingency tables ──────────────────── Number of table is 1 ──
#> $`am vs gear`
#>    gear
#> am        3       4       5
#>   0 0.46875 0.12500 0.00000
#>   1 0.00000 0.25000 0.15625
#> 
#> ── Chi-squared contingency table tests ──────────── Number of table is 1 ──
#>   variable_1 variable_2 statistic      p.value df
#> 1         am       gear  20.94467 2.830889e-05  2
```

In the mtcars data frame, gear and am are categorical variables, but they are coded as numeric variables. So, I called dlookr::compare_category() after performing the type conversion of these two variables.

Instead, I'll create a function that finds the non-occurring case among all combinations of categorical variables. If you explicitly describe numeric variables like gear and am, it will calculate them. 

Best Regards,
Choonghyun

**Comment by SchmidtPaul** [comment]
@choonghyunryu 

Thanks for your answer. I understand your arguments and agree with you that during my workflow it makes sense to 

- use one function (=`dlookr::describe()`) to describe the distribution of numeric variables (per category) that are present in the dataset and 
- use another function (=`dlookr::compare_category()`) to find missing cases in all possible combinations of categorical variables.

However, currently I am using `dlookr` to produce descriptive output tables for reports and in certain situations I find it more efficient to produce a single table like the one in my first comment. It provides both information in one table.

gear|am|variable|n|na|mean|sd|...
-|-|-|-|-|-|-|-
4|1|mpg|8|0|26.3|5.41|... 
4|0|mpg|4|0|21.0|3.07|... 
3|1|mpg|0|-|-|-|-|-|-|-|-|...    
3|0|mpg|15|0|16.1|3.37|...
5|1|mpg|5|0|21.4|6.66|...
5|0|mpg|0|-|-|-|-

**Comment by choonghyunryu** [comment]
@SchmidtPaul 

thank you. accept your  recommendation.
I'll put the functionality of that option in the next version as per your recommendation.

**Comment by choonghyunryu** [comment]
@SchmidtPaul

I implemented the functionality you asked for in version 0.5.5.9000 of dlookr today.
However, the argument name 'show.missing.combinations' is too long, so the argument name 'all.combinations' is used.

After adding a few other features, I'll submit it to CRAN around the end of January.

``` r
library(dplyr)

mtcars %>%
    group_by(gear, am) %>%
    dlookr::describe(mpg, all.combinations = TRUE)
#> # A tibble: 6 x 28
#>   variable  gear    am     n    na  mean    sd se_mean   IQR skewness kurtosis
#>   <chr>    <dbl> <dbl> <dbl> <int> <dbl> <dbl>   <dbl> <dbl>    <dbl>    <dbl>
#> 1 mpg          3     0    15     0  16.1  3.37   0.871  3.9   -0.0910   -0.381
#> 2 mpg          3     1     0    NA  NA   NA     NA     NA     NA        NA    
#> 3 mpg          4     0     4     0  21.0  3.07   1.53   4.35   0.0529   -3.79 
#> 4 mpg          4     1     8     0  26.3  5.41   1.91   9.6    0.352    -1.97 
#> 5 mpg          5     0     0    NA  NA   NA     NA     NA     NA        NA    
#> 6 mpg          5     1     5     0  21.4  6.66   2.98  10.2    0.556    -1.83 
#> # … with 17 more variables: p00 <dbl>, p01 <dbl>, p05 <dbl>, p10 <dbl>,
#> #   p20 <dbl>, p25 <dbl>, p30 <dbl>, p40 <dbl>, p50 <dbl>, p60 <dbl>,
#> #   p70 <dbl>, p75 <dbl>, p80 <dbl>, p90 <dbl>, p95 <dbl>, p99 <dbl>,
#> #   p100 <dbl>
```

<sup>Created on 2022-01-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
