### ISSUE TITLE
the result do not contain the minimum value of the sequence.

### ISSUE THREAD

**Issue by Green-16** [choonghyunryu/dlookr#6]
hello , the below code  contain a bug .

`library(dlookr)`
`a <-  c(1,1,2,  5,5,5,  7,8,100)`
`t=binning(a,nbins=2,type="quantile")`
`print(t)`

it will not contain the value  "1" , 
In your code,                        `  fct <- cut(a, breaks = breaks) `
I think  we should write       `  fct <- cut(a, breaks = breaks,include.lowest = TRUE)`

best regards

**Comment by choonghyunryu** [comment]
Thanks Green-16.

The bug was modified in dlookr 0.3.9. 
Thank you for offering me a solution.

> library(dlookr)
> a <- c(1, 1, 2, 5, 5, 5, 7, 8, 100)
> t <- binning(a, nbins = 2, type = "quantile")
> print(t)
binned type: quantile
number of bins: 2
x
  [1,5] (5,100] 
      6       3 

best regards
