### ISSUE TITLE
`eda_web_report()` with `target` variable throws error

### ISSUE THREAD

**Issue by ashirwad** [choonghyunryu/dlookr#65]
Here's the reprex:

``` r
library(dlookr)
#> 
#> Attaching package: 'dlookr'
#> The following object is masked from 'package:base':
#> 
#>     transform
heartfailure2 <- dlookr::heartfailure
eda_web_report(heartfailure2, target = "death_event")
#> processing file: eda_temp.Rmd
#> Warning: package 'dplyr' was built under R version 4.0.5
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
#> Quitting from lines 361-373 (eda_temp.Rmd)
#> Error: Can't subset columns that don't exist.
#> x Column `variable` doesn't exist.
```

<sup>Created on 2022-04-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by choonghyunryu** [comment]
thanks @ashirwad, 

Thanks for your report. I found the cause of this issue. And after fixing it, I will put it on github.
If you can't wait for a patched version, you should use version 0.5.4. This version will not cause an error.

**Comment by ashirwad** [comment]
Thanks, @choonghyunryu for building this excellent package as well as fixing this issue!

**Comment by choonghyunryu** [comment]
@ashirwad,

Version 0.6.0.9000 with bug fixes has been uploaded to github. 
However, since this is a development version, it will be a long time before it will be submitted to CRAN. 
Because there are still many features to be developed.

**Comment by ashirwad** [comment]
Thanks a lot, @choonghyunryu!

**Comment by choonghyunryu** [comment]
It is not registered on CRAN, but has been reflected in the development version on github, so the issue is closed.
