### ISSUE TITLE
Imputation capping with custom values

### ISSUE THREAD

**Issue by tomasjanikds** [choonghyunryu/dlookr#71]
Would it be possible to implement imputation capping in `imputate_outlier()` function with user specified values of caps (probs) ?

To be more precise, if the `probs` argument in `caps` variable would be available as parameter instead of fixed values of lowest/highest 5%.

```
get_capping <- function() {
    hinges <- quantile(data, probs = c(0.25, 0.75), na.rm = TRUE)
    caps <- quantile(data, probs = c(0.05, 0.95), na.rm = TRUE)

    whisker <- 1.5 * diff(hinges)

    data[data < (hinges[1] - whisker)] <- caps[1]
    data[data > (hinges[2] + whisker)] <- caps[2]
    data
  }
```

Sometimes, there are circumstances when the user need to use different ntile for replacing outliers.

**Comment by choonghyunryu** [comment]
@tomasjanikds,

Oh that's a great idea.

I'll modify the get_capping() function to allow the user to change probs. The default is c(0.05, 0.95), but if the user changes probs it will be cappinned to the desired value.

**Comment by choonghyunryu** [comment]
It's been a month since version 0.6.0, which reflects the requirements, has already been registered on CRAN, so I close the issue.
