### ISSUE TITLE
plot_outlier errors out when diagnose_report is run against a dataset with a numeric column that is null

### ISSUE THREAD

**Issue by rhinomlbox** [choonghyunryu/dlookr#8]
dlookr (v.0.3.9)
plot_outlier errors out when diagnose_report is run against a dataset with a numeric column where all values are N/A

**Here's the traceback:**

Quitting from lines 216-252 (Diagnosis_Report.Rmd) 
Error in plot.window(xlim = xlim, ylim = ylim, log = log, yaxs = pars$yaxs) : 
  need finite 'ylim' values
In addition: Warning messages:
1: In min(x) : no non-missing arguments to min; returning Inf
2: In max(x) :
 Error in plot.window(xlim = xlim, ylim = ylim, log = log, yaxs = pars$yaxs) : 
  need finite 'ylim' values 
31.
plot.window(xlim = xlim, ylim = ylim, log = log, yaxs = pars$yaxs) 
30.
bxp(list(stats = structure(c(NA_real_, NA_real_, NA_real_, NA_real_, 
NA_real_), .Dim = c(5L, 1L)), n = 0, conf = structure(c(NA_real_, 
NA_real_), .Dim = 2:1), out = numeric(0), group = numeric(0), 
    names = ""), notch = FALSE, width = NULL, varwidth = FALSE,  ... 
29.
do.call("bxp", c(list(z, notch = notch, width = width, varwidth = varwidth, 
    log = log, border = border, pars = pars, outline = outline, 
    horizontal = horizontal, add = add, at = at), args[namedargs])) 
28.
boxplot.default(x, main = "With outliers", col = col) 
27.
boxplot(x, main = "With outliers", col = col) 
26.
plot_outliers(df, x, col) 
25.
FUN(X[[i]], ...) 
24.
lapply(vars[idx_numeric], function(x) plot_outliers(df, x, col)) 
23.
plot_outlier_impl(.data, vars, col) 
22.
plot_outlier.data.frame(edaData, variables[i]) 
21.
plot_outlier(edaData, variables[i]) at <text>#26
20.
eval(expr, envir, enclos) 
19.
eval(expr, envir, enclos) 
18.
withVisible(eval(expr, envir, enclos)) 
17.
withCallingHandlers(withVisible(eval(expr, envir, enclos)), warning = wHandler, 
    error = eHandler, message = mHandler) 
16.
handle(ev <- withCallingHandlers(withVisible(eval(expr, envir, 
    enclos)), warning = wHandler, error = eHandler, message = mHandler)) 
15.
timing_fn(handle(ev <- withCallingHandlers(withVisible(eval(expr, 
    envir, enclos)), warning = wHandler, error = eHandler, message = mHandler))) 
14.
evaluate_call(expr, parsed$src[[i]], envir = envir, enclos = enclos, 
    debug = debug, last = i == length(out), use_try = stop_on_error != 
        2L, keep_warning = keep_warning, keep_message = keep_message, 
    output_handler = output_handler, include_timing = include_timing) 
13.
evaluate::evaluate(...) 
12.
evaluate(code, envir = env, new_device = FALSE, keep_warning = !isFALSE(options$warning), 
    keep_message = !isFALSE(options$message), stop_on_error = if (options$error && 
        options$include) 0L else 2L, output_handler = knit_handlers(options$render, 
        options)) 
11.
in_dir(input_dir(), evaluate(code, envir = env, new_device = FALSE, 
    keep_warning = !isFALSE(options$warning), keep_message = !isFALSE(options$message), 
    stop_on_error = if (options$error && options$include) 0L else 2L, 
    output_handler = knit_handlers(options$render, options))) 
10.
block_exec(params) 
9.
call_block(x) 
8.
process_group.block(group) 
7.
process_group(group) 
6.
withCallingHandlers(if (tangle) process_tangle(group) else process_group(group), 
    error = function(e) {
        setwd(wd)
        cat(res, sep = "\n", file = output %n% "") ... 
5.
process_file(text, output) 
4.
knitr::knit(knit_input, knit_output, envir = envir, quiet = quiet, 
    encoding = encoding) 
3.
rmarkdown::render(paste(path, rmd, sep = "/"), output_format = prettydoc::html_pretty(toc = TRUE, 
    number_sections = TRUE), output_file = paste(path, output_file, 
    sep = "/")) 
2.
diagnose_report.data.frame(sample, output_format = "html") 
1.
diagnose_report(sample, output_format = "html")

**Comment by choonghyunryu** [comment]
dear rhinomlbox,

Thank you for your reporting.
Fixed plot_outlier () error in numeric variable with all observations NA in dlookr 0.3.11.

**Comment by choonghyunryu** [comment]
Fixed plot_outlier()
