### ISSUE TITLE
Error in imputae_summary(impu) : object 'smmry' not found

### ISSUE THREAD

**Issue by SaraJKerr** [choonghyunryu/dlookr#9]
Transformation report errors out at lines 146-183 with the following error: Error in imputae_summary(impu) : object 'smmry' not found

**Comment by choonghyunryu** [comment]
Dear SaraJKerr,

I'm very sorry for the late response to your report.

Install the 0.3.11 version of github.
However, if the same error occurs, please provide the data characteristics.
It is difficult to find the cause only by error message.

Have a good day.

**Comment by SaraJKerr** [comment]
Dear choonghyunryu
Thank you for looking at this. I will install the new version of github and try again. I did have a look at the source code but couldn’t see why this error occurred. I’ll let you know more detail regarding the error if it still happens.

The package is great overall and has been very useful for my work, thank you very much for creating it.

Kind regards,
Sara

**Comment by choonghyunryu** [comment]
Dear Sara,

Thank you for your attention and encouragement.
Please contact us immediately if an error occurs.
And if I know the structure of the data, I can easily identify the cause.

Also advise any new features you'd like to see in the package.
Thank you.

Best Regards,
choonghyun

**Comment by choonghyunryu** [comment]
Dear Sara,

close. If there is a similar error, please register again in Issue.

Best Regards,
choonghyun
