### ISSUE TITLE
degrees of freedom on eda report wrong?

### ISSUE THREAD

**Issue by Busler13** [choonghyunryu/dlookr#98]
Hi! Loving this package! Thank you!

I think the degrees of freedom may be calculating incorrectly for the chisq indepedence test for categorical variables.

I have two categorical variables each with 2 levels. The df on the eda web report says 4 but when I run a chisq test just in the R console the df is 1.

Best!

**Comment by choonghyunryu** [comment]
@Busler13,

Thanks you so much.
fixed with 0.6.3.9002 in github.

**Comment by Busler13** [comment]
Thank you!!!JessicaOn Jul 17, 2023, at 23:32, Choonghyun Ryu ***@***.***> wrote:﻿
@Busler13,
Thanks you so much.
fixed with 0.6.3.9002 in github.
